apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: ingress-nginx
  version: 4.7.1
  repo: https://kubernetes.github.io/ingress-nginx
  namespace: ingress-nginx
  releaseName: ingress-nginx
